const path = require('path');
const fs = require('fs');
const os = require('os');
const { execFileSync } = require('child_process');
const { FileLane } = require('file-lane');
const { UxConfig, CompileMode } = require('@aiot-toolkit/aiotpack');

function isPrivateLanIp(address) {
  const octets = address.split('.').map(Number);
  if (octets.length !== 4 || octets.some(n => !Number.isInteger(n) || n < 0 || n > 255)) return false;
  return octets[0] === 10 ||
    (octets[0] === 172 && octets[1] >= 16 && octets[1] <= 31) ||
    (octets[0] === 192 && octets[1] === 168);
}

function detectLanIp() {
  const interfaces = os.networkInterfaces();
  let preferred = '';
  if (process.platform === 'darwin') {
    try {
      const route = execFileSync('route', ['get', 'default'], { encoding: 'utf8' });
      preferred = (route.match(/^\s*interface:\s*(\S+)/m) || [])[1] || '';
    } catch (_) {}
  }
  const names = [preferred, 'en0', 'en1', 'wlan0', 'Wi-Fi', ...Object.keys(interfaces)]
    .filter((name, index, all) => name && all.indexOf(name) === index && !/^(utun|tun|tap|veth|docker|bridge|lo)/i.test(name));
  for (const name of names) {
    for (const item of interfaces[name] || []) {
      if (item.family === 'IPv4' && !item.internal && isPrivateLanIp(item.address)) return item.address;
    }
  }
  return null;
}

function detectBonjourHost() {
  if (process.platform !== 'darwin') return null;
  try {
    const name = execFileSync('scutil', ['--get', 'LocalHostName'], { encoding: 'utf8' }).trim();
    return /^[a-z0-9-]+$/i.test(name) ? `${name}.local` : null;
  } catch (_) {
    return null;
  }
}

async function writeServerConfig() {
  const lanIp = detectLanIp();
  // An explicit server URL is portable and must not embed this computer's name.
  const bonjourHost = process.env.WATCH_SERVER_URL ? null : detectBonjourHost();
  const selected = process.env.WATCH_SERVER_URL ||
    (lanIp && `http://${lanIp}:8000`) ||
    (bonjourHost && `http://${bonjourHost}:8000`);
  if (!selected || !/^https?:\/\/[^\s/]+(?::\d{1,5})?$/.test(selected)) {
    throw new Error('无法确定手表可访问的服务地址。请设置 WATCH_SERVER_URL=http://电脑局域网IP:8000 后重试。');
  }
  const url = selected.replace(/\/$/, '');
  const parsed = new URL(url);
  const discoveryHosts = bonjourHost
    ? [`${parsed.protocol}//${bonjourHost}:${parsed.port || (parsed.protocol === 'https:' ? '443' : '80')}`]
    : [];
  fs.writeFileSync(path.join(__dirname, 'src/common/config.js'),
    `// Generated by watch/pack.js. Override with WATCH_SERVER_URL when building.\nexport const SERVER_URL = ${JSON.stringify(url)};\nexport const POLL_INTERVAL_MS = 2000;\n`);
  fs.appendFileSync(path.join(__dirname, 'src/common/config.js'),
    `export const DISCOVERY_HOSTS = ${JSON.stringify(discoveryHosts)};\n`);
  console.log('📡 手表默认服务地址:', url);
  if (discoveryHosts.length) console.log('🔎 可尝试的电脑名称:', discoveryHosts[0]);
}

async function buildMode(mode) {
  const projectPath = __dirname;
  const config = new UxConfig(projectPath);
  const tempPath = path.join(projectPath, config.output);

  if (fs.existsSync(tempPath)) {
    fs.rmSync(tempPath, { recursive: true, force: true });
  }

  const compilerOption = {
    projectPath: tempPath,
    mode: mode,
    sourceRoot: 'src',
    outputPath: 'build',
    releasePath: 'dist'
  };

  return new Promise((resolve, reject) => {
    const lane = new FileLane(config, projectPath, compilerOption, {
      onBuildSuccess: (data) => resolve(data),
      onBuildError: (err) => reject(err),
      onLog: () => {}
    });
    lane.start();
  });
}

async function main() {
  await writeServerConfig();
  const target = process.argv[2];
  const distDir = path.join(__dirname, 'dist');

  if (target === 'release') {
    console.log('🔨 正在打包 Xiaomi Vela 专属 [Release] 包...');
    const res = await buildMode(CompileMode.PRODUCTION);
    console.log('✅ Release 打包成功:', res.info?.rpk);
  } else if (target === 'debug') {
    console.log('🔨 正在打包 Xiaomi Vela 专属 [Debug] 包...');
    const res = await buildMode(CompileMode.DEVELOPMENT);
    console.log('✅ Debug 打包成功:', res.info?.rpk);
  } else {
    console.log('🔨 正在构建 Xiaomi Vela 专属应用 (Debug & Release)...');

    // 1. 先构建 Debug 包
    const debugRes = await buildMode(CompileMode.DEVELOPMENT);
    const debugRpkPath = debugRes.info?.rpk;
    const debugBuf = fs.readFileSync(debugRpkPath);
    const debugName = path.basename(debugRpkPath);
    console.log('✅ 1. Debug 包构建完成:', debugName);

    // 2. 再构建 Release 包 (此时 moveBackResult 会覆写 dist 目录)
    const releaseRes = await buildMode(CompileMode.PRODUCTION);
    const releaseName = path.basename(releaseRes.info?.rpk);
    console.log('✅ 2. Release 包构建完成:', releaseName);

    // 3. 将 Debug 包保留写回 dist 目录
    fs.writeFileSync(path.join(distDir, debugName), debugBuf);
  }

  console.log('\n🎉 所有打包工作已完成！产物目录：', distDir);
  for (const f of fs.readdirSync(distDir)) {
    if (f.endsWith('.rpk')) {
      const sz = (fs.statSync(path.join(distDir, f)).size / 1024).toFixed(1);
      console.log(`   📦 ${f} (${sz} KB)`);
    }
  }
}

main().catch(err => {
  console.error('❌ 打包失败:', err);
  process.exit(1);
});
